[project]
name = "deck-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.9",
    "pre-commit>=4.1.0",
    "uvicorn>=0.34.0",
]
