services:

  profile-service:
    build:
      context: ..
      dockerfile: profile-service/Dockerfile
    environment:
      APP_ENV: prod
      APP_CONFIG__DB__URL: ${APP_CONFIG__DB__URL}
      APP_CONFIG__KAFKA__BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8000:8000"
    depends_on:
      pg-profile:
        condition: service_healthy
    networks:
      - profile-network

  pg-profile:
    image: postgres
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
    ports:
      - "${APP_CONFIG__DB__PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${APP_CONFIG__DB__USER}", "-d", "${APP_CONFIG__DB__NAME}"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - profile-network



networks:
  profile-network:
